# theme: jekyll-theme-minimal
remote_theme: crxssed7/minimalist
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Entertainment
description: A list of all the TV Shows, Movies, Comics and Books that I enjoy.<br><br><a href="https://crxssed.dev/"><i class="fa-solid fa-globe"></i> Website</a>
logo: /assets/img/logo.png
color-scheme: dark
sidebar:
  - name: Website
    icon: <i class="fa-solid fa-globe"></i>
    link: https://crxssed.dev/
